# Ejercicio 1 #
nombre = str()
apellido = str()
edad = int()
fechadenacimiento = str()
montomatricula = float()
valor_cuota = int()
cuota = int()
cuota_python = int()
cuota_python_descuento = float()
Titulo = bool()
pago_en_efectivo = str()
Titulo = "True"
cuota = 1000
cuota_python = 12000
print("--- Ingrese sus Datos ---")
print()
nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = int(input("Ingrese su edad: "))
fechadenacimiento = input ("Ingrese su fecha de nacimiento: ")
montomatricula = float(input("Ingrese el monto de la matricula: "))
pago_en_efectivo = str(input("Desea pagar en efectivo la cuota de la materia python? (Si/No): "))
print("=="*50)
print("======== Universidad de Python - Inscripciones ========")
print("=="*50)
print("Nombre completo", "y", "Edad: ", nombre, apellido, edad)
print("Fecha de nacimiento:", fechadenacimiento)
print("Posee Titulo?: ", Titulo)
print("Matricula:", montomatricula)
valor_cuota = int(( montomatricula + cuota))
print("Valor de la cuota" ,valor_cuota)
print("Arancel Mensual materia -Python I-", cuota_python)
if(pago_en_efectivo == "Si"):
    cuota_python_descuento = ((12000 * 15)/100)
    print("Arancel Mensual materia -Python I- con descuento", cuota_python_descuento)
print("=="*50)
("======== Universidad de Python - Inscripciones ========")
print("=="*50)